### ISSUE TITLE
Presentation questions

### ISSUE THREAD

**Issue by wmurphyrd** [vcastro/Ri2b2matchcontrols#1]
Hi, great talk today at AMIA. I have some questions I didn't get a change to ask:

In the osteoporosis results dat viz, there appeared to be some confusion between potential causal factors (e.g. lisinopril) and common therapies (mineral supplements). Was this a limitation just of the visualization, or is it limitation of the models used?

Also, are you planning to submit this package to CRAN?

Thanks!

**Comment by vcastro** [comment]
Hi Will,

Thanks for the interest in the software.

Yes, the visualization y-axis is -log10 p-value so does not include the direction of the effect.  I’ve been working on making this more clear in the graph.  Attached see the results in tabular form.  Ideally we should be excluding common treatments for osteoporosis.  In practice, however, patients with osteopenia or risk of osteoporosis also get treatments prior to the incident osteoporosis diagnosis.  You could expand the disease definition or change your treatment window to help with this.

RE: CRAN – that is the ultimate goal but I need to do some more work to be done before that.  I’d actually like to integrate functions to directly pull the data from i2b2 to avoid having to write out large flat files.

I’m around for the afternoon if you want to discuss further or have other questions.

Thanks,
Victor

**Comment by wmurphyrd** [comment]
Ah, p-value on the Y axis. Makes sense. Thanks!
